host/sudo.go
In rare cases, sudo gets blocked forever, and tests timeout. The root cause was that sometimes, stderr receives a write which conttains BOTH the `SudoOk` string and the beginning of the command output. This PR fixes this for both `SudoOk` and `Prompt`, so that those are stripped out, and the remaining output is passed along.
```
⚡ Sudo
sudo ok (0d2ba645a243c2c7cbd579d0a026899980dcd58130bedb77ac26138ea28397c2)sh: 1: cannot create /tmp/TestSudoWriteFilesyscall.EISDIR4032744780/001/foo: Is a directory
github.com/fornellas/resonance/host	coverage: 87.1% of statements in ./...
github.com/fornellas/resonance/log	coverage: 56.7% of statements in ./...
panic: test timed out after 2s
running tests:
TestSudo (2s)
TestSudo/WriteFile (2s)
TestSudo/WriteFile/syscall.EISDIR (2s)
goroutine 514 …
```
=> Fix sudo race condition

.github/workflows/build-darwin.yaml, .github/workflows/build-linux.yaml, build.sh
Test whether `make clean` actually does what it is supposed to.
=> Add clean test

cli/lib/lib.go, cli/lib/lib_darwin.go, cli/lib/lib_linux.go, host/docker_unix.go, host/local/local_unix.go, resource/plan.go, resource/types/apt_package.go
Support targeting Docker containers (and push some random fixes).
=> Add Docker host support

resource/state.go, resource/types/apt_package.go
use `apt-cache` instead of `dpkg-query`, as the latter does not have a stable interface for package status.
=> Fix apt package

.github/workflows/build-darwin.yaml, .github/workflows/build-linux.yaml
=> Fix cache save

cmd/test/resources/individual.go, cmd/test/resources/mergeable.go, resources/action.go, resources/apt_package.go, resources/file.go, resources/resource.go
@ricardo6142dh hopefully these names make more sense :-D
=> Rename resource functions

Makefile
=> Fix LINT_GOVULNCHECK_DISABLE=1

resources/resources.go, resources/resources_test.go
These extra functions are gonna be used on a subsequent PRs that implements plan, apply etc. It was just split into this PR to ease code review.
---
**Stack**:
- #95
- #98
- #97
- #96
- #94
- #91
- #90
- #89 ⬅
=> Add extra resources functions

cmd/validate.go, internal/blueprint/blueprint.go, internal/blueprint/blueprint_graphviz.go, internal/blueprint/step.go, internal/store/common_linux_test.go
This PR does some small refactoring of the Blueprint interface, to support subsequent PRs which will implement plan, apply commands.
---
**Stack**:
- #116
- #107
- #108
- #111
- #110
- #109
- #106
- #105
- #104 ⬅
=> Refactor Blueprint interface

internal/blueprint/blueprint_test.go, internal/blueprint/step.go, internal/blueprint/step_linux_test.go
Ditto.
---
**Stack**:
- #116
- #107
- #108
- #111 ⬅
=> Add Blueprint tests

cmd/helpers_linux_test.go, cmd/plan.go, cmd/plan_linux_test.go, cmd/validate_linux_test.go, internal/blueprint/step.go, internal/plan/prep.go, internal/plan/prep_linux_test.go, internal/resources/load.go
This PR finally adds the plan command, building on top of all previous PRs on the stack.
Closes #26.
---
**Stack**:
- #116
- #107 ⬅
=> Add plan command

internal/host/agent_http_client.go, internal/host/agent_server_http/main_linux.go
The HTTP agent is using a yaml library that has proven to be terrible for CPU & memory usage. When testing #159, I found peaks of the agent consuming *~30G* (yes, with a "G") of RAM, a taking ~1min to run. Changing from yaml to go's own json library, we go to well behaved memory usage proportinoal to the ~20M of data we have and ~6s to run.
Here's a memory profile I took, while the agent was in the process of getting to ~30G peak:
@ricardo6142dh this definitely closes the gap to gRPC, but I do expect gRPC to beat JSON on CPU usage in the end.
---
**Stack**:
- #159
- #165
- #163 ⬅
=> ~10x faster & ~700x less memory for the HTTP agent

internal/host/agent_grpc_client.go, internal/host/agent_grpc_client_linux_test.go, internal/host/agent_server_grpc/main_linux.go, internal/host/agent_server_grpc/proto/service.proto
This PR introduces several key file system operations, including chmod, chown, lookup, mkdir, lstat, readDir, readFile, and remove. Each function is implemented to expand resonance capabilities in handling file system tasks directly.
=> Implementing GRPC functions

host/host.go, internal/host/agent_grpc_client.go, internal/host/agent_http_client.go, internal/host/agent_server_grpc/main_linux.go, internal/host/agent_server_grpc/proto/service.proto, internal/host/agent_server_http/main_linux.go, internal/host/cmd_run.go, internal/host/cmd_run_linux_test.go, internal/host/local_linux.go, internal/host/test_helpers_linux.go
Ditto. We need this to support managing symlinks.
commit-id:bb7fbd72
---
**Stack**:
- #159
- #165
- #179
- #178
- #176
- #170 ⬅
=> Add Host.Readlink

internal/host/agent_http_client.go, internal/host/agent_server_grpc/main_linux.go, internal/host/agent_server_grpc/proto/service.proto
This PR is a NOOP, just reordering implementations of `Host` to match the interface declaration order, to help with maintainability (and OCD).
---
**Stack**:
- #159
- #165
- #179
- #178 ⬅
=> "Defrag" Host implementations

cmd/apply.go, cmd/plan.go, cmd/validate.go, host/host.go, host/types.go, internal/host/agent_grpc_client.go, internal/host/agent_grpc_client_linux_test.go, internal/host/agent_http_client.go, internal/host/agent_http_client_linux_test.go, internal/host/agent_server_grpc/main_linux.go, internal/host/agent_server_grpc/proto/service.proto, internal/host/cmd_run_linux_test.go, internal/host/docker_unix.go, internal/host/local_linux.go, internal/host/local_linux_test.go, internal/host/ssh.go, internal/host/ssh_linux_test.go, internal/host/sudo.go, internal/host/sudo_linux_test.go
Now it gracefully stops without leaving any process behind.
=> Fix gRPC agent shutdown

host/host.go, internal/host/agent_client.go, internal/host/agent_server/main_linux.go, internal/host/agent_server/proto/service.proto, internal/host/cmd_run.go, internal/host/cmd_run_linux_test.go, internal/host/local_linux.go, internal/host/test_helpers_linux.go
Add this as part of the interface, as it'll be required by #165.
---
**Stack**:
- #159
- #209
- #208
- #215
- #216
- #202
- #211
- #214
- #212
- #204
- #213
- #210
- #207
- #206
- #199
- #203
- #200
- #197 ⬅
=> Add Host.Symlink

host/host.go, internal/host/agent_client.go, internal/host/agent_server/main_linux.go, internal/host/agent_server/proto/service.proto, internal/host/cmd_run.go, internal/host/cmd_run_linux_test.go, internal/host/local_linux.go, internal/host/test_helpers_linux.go
Add this as part of the interface, as it'll be required by #165.
---
**Stack**:
- #159
- #209
- #208
- #215
- #216
- #202
- #211
- #214
- #212
- #204
- #213
- #210
- #207
- #206
- #199
- #203
- #200 ⬅
=> Add Host.Getuid/Getgid

internal/host/agent_server/main_linux.go, internal/host/cmd_run.go, internal/host/lib/readdir_linux.go, internal/host/local_linux.go
As doing so improves the error message.
---
**Stack**:
- #159
- #209
- #208
- #215
- #216
- #202
- #211
- #214
- #212
- #204
- #213
- #210
- #207
- #206
- #199
- #203 ⬅
=> Change errors to fs.PathError

go.mod, go.sum, host/host.go, internal/host/agent_client_wrapper.go, internal/host/agent_server/main_linux.go, internal/host/agent_server/proto/service.proto, internal/host/lib_linux_test.go, internal/host/local_linux.go
Add this as part of the interface, as it'll be required by #165.
---
**Stack**:
- #159
- #209
- #208
- #215
- #216
- #202
- #211 ⬅
=> Add Host.Mknod

internal/host/agent_server/main_linux.go, internal/host/agent_server/proto/service.proto
Remove some response objects that were not being used.
---
**Stack**:
- #159
- #209
- #208
- #222 ⬅
=> Simplify protobuf

host/agent_client_wrapper_linux_test.go, host/docker_unix_test.go, host/lib_linux_test.go, host/lib_unix_test.go, host/local_linux_test.go, host/ssh_linux_test.go, host/sudo_wrapper_linux_test.go
Ditto
---
**Stack**:
- #159
- #209
- #208
- #226
- #225
- #224 ⬅
=> Simplify temporary directory in tests

host/agent_client_wrapper.go, host/lib_linux_test.go
Ditto
---
**Stack**:
- #159
- #209
- #208
- #226
- #225 ⬅
=> Fix ReadFile with empty file

host/ssh.go
**Stack**:
- #209
- #241
- #246 ⬅
=> Fix fingerprint validatiton

cmd/lib.go, cmd/lib_darwin.go, cmd/lib_linux.go
Ditto
---
**Stack**:
- #209
- #241
- #247 ⬅
=> Use Cobra to define target flag constraints

.github/workflows/ci.yaml
https://github.com/ejoffe/spr proved to be... quircky and often unreliable, so let's drop this job.
=> Drop SPR job

host/agent_client_wrapper.go, host/agent_server/main_linux.go, host/agent_server/proto/service.proto, host/docker_unix.go, host/lib/host_linux.go, host/lib_unix_test.go, host/ssh.go, host/types/cmd.go
=> Fix ExitCode type

.github/workflows/ci.yaml, Makefile, cmd/apply.go, cmd/helpers_linux_test.go, cmd/plan.go, cmd/validate.go, host/agent_client_wrapper.go, host/agent_server/main_linux.go, host/host_linux_test.go, host/lib/host_linux.go, host/ssh.go, host/ssh_linux_test.go, host/sudo_wrapper.go, resources/load.go
Ditto.
Also fixing concurrency on GH jobs, so that we don't let old PR commits job run: the're cancelled, and the latest one is run instead.
=> Fix defer functions error catching

cmd/apply.go, cmd/lib_store.go, cmd/lib_store_linux.go, cmd/plan.go
Accept relative paths for local store.
=> Fix local store with relative path

.github/workflows/ci.yaml, cmd/lib_store_darwin.go
And let's try make PR merge requrie on it, as coveralls job seems to be skipped if any other job fail, and merge goes on. Hopefully this new ci job will fail if one job fail, and prevent the merge.
=> Add CI job

host/agent_client_wrapper.go, host/agent_server/main_linux.go, host/base_host_unix_test.go, host/sudo_wrapper.go, host/sudo_wrapper_linux_test.go
We were not passing that to the server.
=> Fix stdin EOF for agent
