fornellas/resonance

- resource/bundle.go
- resource/diff.go
- resource/diff_test.go
- resource/plan.go
- resource/resource.go
- resource/types/apt_package.go
For cases such as `APTPackage` and no version set, any existing version sholud be accepted, but as it stands currently `"1.0"` != `""`, so things fail.
This PR adds an interface for such resource types, so they can define their own definition of diff two states to account for such idiosyncrasies.
> Fix resource diff

- internal/host/agent_client.go
- internal/host/cmd_run.go
- internal/host/cmd_run_linux_test.go
- internal/host/docker_unix.go
- internal/host/ssh.go
- internal/host/sudo.go
- internal/host/sudo_linux_test.go
The `baseRun` type had a pretty bad name and was missing documentation. This PR should address this, hopefully making the code easier to understand.
It is also moving all `New*` methods closer to the type, following the order that go documentation uses.
> Rename baseRun to cmdRun

- Makefile
- README.md
I've been having a blast with https://github.com/golang/tools/tree/master/gopls, and using it with the development shell makes things a lot easier. I've realised that this _should_ just work on MacOS as well, so... let's give it a try.  @ricardo6142dh can you please help test that by doing `gmake shell`?
This PR also updates the documentation on development, covering this case, and generally improving things.
> Enable development shell for MacOS

- cmd/validate.go
- internal/resources/node.go
Build on top of @gfechio changes, to move the `String()` logic to the right place.
```
$ ./resonance.linux.amd64 validate --localhost foo.yaml 
🔍 Validating
path: foo.yaml
host: localhost
📝 Loading file
path: foo.yaml
📦 Resources
resources:
1. APTPackages: bar,foo
2. File: /tmp/foo
3. File: /tmp/bar
🎆 Validation successful
```
PS: I reckon that "Nodes" ain't the best name, and I'd like to tackle that on a future PR.
> Improve Nodes String logic

- internal/resources/host_state_graphviz.go
- internal/resources/node.go
It looks like Graphviz can't be bulit on 386 https://github.com/fornellas/resonance/actions/runs/10228304747/job/28300680133#step:5:102:
```
../.cache/resonance/GOMODCACHE/github.com/goccy/go-graphviz@v0.1.3/internal/ccall/cdt.go:131:11: cannot use *(*[wordSize]byte)(unsafe.Pointer(v.c)) (variable of type [8]byte) as [4]byte value in assignment (compile)
../.cache/resonance/GOMODCACHE/github.com/goccy/go-graphviz@v0.1.3/internal/ccall/cdt.go:241:11: cannot use *(*[wordSize]byte)(unsafe.Pointer(header.Data)) (variable of type [8]byte) as [4]byte value in assignment (compile)
../.cache/resonance/GOMODCACHE/github.com/goccy/go-graphviz@v0.1.3/internal/ccall/cdt.go:250:11: cannot use *(*[wordSize]byte)(unsafe.Pointer(v.c)) (variable of type [8]byte) as [4]byte value in assignment (compile) …
```
> Fix 32 bit builds

- README.md
@gfechio you asked about this, it exists, but was missing from `README.md`. Let's add it.
> Add GO_BUILD_AGENT_NATIVE_ONLY=1 to docs

- cmd/plan.go
- internal/blueprint/blueprint.go
- internal/blueprint/blueprint_test.go
- internal/store/host.go
- resources/file.go
- resources/resources.go
- resources/resources_test.go
Follow up to #60.
Implement a basic `Store` that's able to store the `Blueprint` and load it after. This let's the plan command move a bit further ahead. Next & final stop, actually calculating the plan (last TODO in the code).
This required fixing various random bugs, and implement marshaling for some types. These marshalings are a bit tricky, as the structs have the interface references, but we must marshal the contrete type, and unmarshal it back to the interface. I've added tests to cover that.
> Implement basic host store

- .github/workflows/build-linux.yaml
The update job is failing with a weird staticcheck error, that I could not reproduce locally.
This PR adds a step to diff the changes, which should make it easier to see what changed, and reproduce locally.
Part of #76.
> Diff updates

- Makefile
- internal/host/agent_server/agent_linux.go
- internal/host/local_linux.go
- internal/host/local_run/local_run_unix.go
I've noticed the build started to take longer recently... and [found the culpid](https://github.com/fornellas/resonance/issues/17#issuecomment-2267747277) (thanks `git bisect`): https://github.com/fornellas/resonance/commit/30ad492345a6123ad59449a89010458f80c93ca3 balooned the agent size.
I'm not totally sure why that is, as I'd expect the go compiler to not include all non-used symbols in the agent package, but... I've also read some coments on "if you use reflect all bets are off", so... ¯\_(ツ)_/¯
Whatever the case... let's rollback the change, and get back to tame levels.
I've also added a check on CI, to prevent agent size from balooning without notice again.
Closes #17.
> Tame agent size

- .github/workflows/update_deps.yaml
#79 fixed what needed fixing... now this:
https://github.com/fornellas/resonance/actions/runs/10540238106/job/29204674730#step:16:100
```
Pushing pull request branch to 'origin/create-pull-request/patch'
/usr/bin/git push --force-with-lease origin create-pull-request/patch:refs/heads/create-pull-request/patch
remote: Permission to fornellas/resonance.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/fornellas/resonance/': The requested URL returned error: 403
Error: The process '/usr/bin/git' failed with exit code 128
```
🤬 GitHub Actions... guesswork, merge, fail, rinse, repeat and https://noyaml.com/ hell...
> Fix update job permissions

- .github/workflows/pull_request.yaml
- .spr.yml
GitHub is pretty terrible to deal with stacked PRs. I've found https://github.com/ejoffe/spr which seems promissing to help aliviate the pain.
This PR:
- adds the configuration for it (which the CLI creates when we run it)
- sets the pull_request job to run on PRs from spr.
- adds a build signal that fails if the target branch is spr's, to prevent any accidental merge (as spr requires that merges happen from bottom up, always).
commit-id:fc3c74d2
---
**Stack**:
- #95
- #98
- #97
- #96
- #94
- #91
- #90
- #89
- #92 ⬅
> Add stacked PRs support

- .github/workflows/pull_request.yaml
The pull request job was not triggered here
https://github.com/fornellas/resonance/pull/90
but sohuld have. The reason is likely the `origin/` prefix that must be dropped (the branch name is actually `spr/master/6b80a22d`, no prefix).
The check to block merges against `spr/master/*` was also broken, attempting to fix it.
---
**Stack**:
- #95
- #98
- #97
- #96
- #94
- #91
- #90
- #89
- #99 ⬅
> Fix pull_request job

- internal/host/agent_client.go
- internal/host/cmd_run.go
- internal/host/ssh.go
- internal/host/sudo.go
- internal/resources/load.go
- log/log.go
The logging handler for console supports indentation, which can be interpreted as a "section".
As of now, indentation can be arbitrarily created, but there's nothing enforcing that ther's any sort of title. This can result in odd outputs.
Eg: instead of :
```
top message
mid message
lower message
```
if nothing is loggen on mid, we end up with:
```
top message
lower message
```
which looks odd. This can happen when for example, mid is only logging on debug, and we're running on info.
This PR (for the most part) addresses that, by changing the interface to "ask for a section title", and enforces the logging of the title as info.
---
**Stack**:
- #95
- #98
- #97
- #96
- #94
- #91
- #90 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI …
> Fix log indentation

- .github/workflows/build-linux.yaml
- Makefile
This PR adds a `update-deps` Makefile target, to simplify the interface of updatting things.
This will be useful on #75, which now requires [an ad-hoc version on the Makefile](https://github.com/fornellas/resonance/pull/75/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R200).
> Add update-deps make target

- log/log.go
PR #90 introduced sections and logs as info when a new section is created. However, if the log level is higher (eg: warn), then the section won't be logged, and any higher level log (eg: warn, error) will be indented without a section.
This PR fixes that, by only enabling indentation when the level info is enabled.
---
**Stack**:
- #116
- #107
- #108
- #111
- #110
- #109
- #106
- #105
- #104
- #103
- #102
- #101
- #112 ⬅
- #126
- #129
> Fix console logger indentation for level > info

- .github/workflows/pull_request.yaml
- .github/workflows/push.yaml
On #75 we dropped arm 32bit support (we'll decide on https://github.com/fornellas/resonance/issues/124 what to do about it). There was left over references, which are [breaknig the build](https://github.com/fornellas/resonance/actions/runs/10646571228):
```
The workflow is not valid. .github/workflows/push.yaml (Line: 57, Col: 9): Job 'release' depends on unknown job 'linux_arm'. .github/workflows/push.yaml (Line: 100, Col: 9): Job 'coveralls' depends on unknown job 'linux_arm'.
```
This PR fixes that, by erasing all arm 32 references.
---
**Stack**:
- #116
- #107
- #108
- #111
- #110
- #109
- #106
- #105
- #104
- #103
- #102
- #101
- #130
- #126
- #129 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected …
> Fix build: (fully remove arm 32bit)

- internal/version.go
ATM we only have the git tag in the version, let's add GOOS and GOARCH as well, which can be useful in the future.
> Add os & arch to version

- Makefile
We had a stray `ci` target there... let's get rid of it. It was just making the first build super slow, for no benefit.
> Fix rrb-dev

- .gitignore
- Makefile
- internal/host/agent_server_grpc/client/main.go
- internal/host/agent_server_grpc/proto/service.proto
- internal/host/agent_server_grpc/server/main.go
Mostly just moving the test grpc agent from #75 to a place that matches the HTTP agent placement.
Bonus:
- Call go build to both client & server, so we can actually easily bulid & manually test them.
- Fix a bug with `RRB_IGNORE_PATTERN` not ignoring generated `.go` files, so RRB would just re-trigger itself and never finish.
commit-id:b4b6383b
---
**Stack**:
- #116
- #107
- #108
- #111
- #110
- #109
- #106
- #105
- #104
- #103
- #102
- #101
- #130
- #126 ⬅
> Move grpc agent to its "final" dentination

- resources/apt_package.go
- resources/file.go
This code is redundant, as we had this logic moved to `resources/resources.go:ValidateResource()`, so it is universally applied to all resource types, no code duplication required.
commit-id:d1ea523e
---
**Stack**:
- #116
- #107
- #108
- #111
- #110
- #109
- #106
- #105
- #104
- #103
- #102
- #101 ⬅
> Drop ad-hoc resource validation on remove=true

- internal/resources/load.go
We now have a method that has extra logic for resource validation, we should not be calling it directly.
---
**Stack**:
- #116
- #107
- #108
- #111
- #110
- #109
- #106
- #105
- #104
- #103 ⬅
> Fix resource validation

- resources/apt_package.go
- resources/file.go
- resources/resources.go
All resource types must have both an "id" field, that uniquely identifies the resource at a host, and a "remove" field, to inform whether it should be... removed.
As of now, both fields are mandatory, but they can live anywhere in the struct, and the Id field, requires a special tag.
This PR simplifies that, enforcing instead that all resources have the first 2 fields as such:
```go
type Foo struct {
FooName string `yaml:"foo_name"`
Remove bool `yaml:"remove,omitempty"`
}
```
which simplifies things quite a bit.
In particular, when marshaling yamls, the id field will be guaranteed to be the first one, which eases understanding.
---
**Stack**:
- #116
- #107
- #108
- #111
- #110
- #109
- #106
- #105 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually …
> Simplify id & remove resource fields

- resources/apt_package.go
- resources/resources.go
- resources/resources_test.go
When comparing some resources, it is not enough to just look "is it the name values". Eg: for a File, if all attributes are the same for 2 resources, then it is the same state. Eg: for APTPackage, if (a) does not require any specific version, but (b) does, then (b) satisfies (a), but (a) does not satisfy (b).
This PR implements this interface, which is required for planning to work.
---
**Stack**:
- #116
- #107
- #108
- #111
- #110
- #109
- #106 ⬅
> Resources: Add Satisfies

- resources/apt_package.go
- resources/file.go
- resources/resources.go
- resources/resources_test.go
Resources must have a field to indicate whether it is there or not. Until now, the word 'remove' has been used. When implementing the plan mechanics, I figured that this term can create confusion in some circunstances.
This PR changes the name 'remove' to 'absent', which when true, indicates... the resource is absent.
---
**Stack**:
- #116
- #107
- #108
- #111
- #110
- #109 ⬅
> Change 'remove' to 'absent'

- internal/plan/plan.go
- internal/plan/plan_test.go
This PR adds the inner mechanics of planning changes. A follow up PR will deal with its inputs:
- The original version of resources.
- The last applied version of resources.
- The target resources.
As a function of these, diffirent things must happen when applying:
- If resource exist on target, but not on last, apply target (over original).
- If resource does not exist on target, but exist on last, apply original (stop managing it).
- If resource exist in target and on last, apply target (over last).
In terms of actions:
- If no change required (following #106 rules), ✅ no action, no diff.
- If changes required, and coming from absent to present, 🔧 create action, with diff from `nil` to target.
- If changes required, and coming from present to absent, 🗑 remove action, diff from previous …
> Add internal/plan

- cmd/apply.go
- cmd/apply_linux_test.go
- internal/plan/plan.go
- resources/resources.go
Follow up to #107 (which added the `plan` command). Now we're _finally_ at the point where things are starting to be functional & testable.
Once this PR merges, we should have all the basic inner workings to calculate all changes, plan and apply them, including all state management (eg: to allow restoring to the original state when we no longer manage a resource).
Getting closer to the first worknig alpha release!
Closes #53.
> Add apply command

- internal/host/cmd_run.go
- internal/host/local_linux.go
- internal/host/local_run/local_run_unix.go
- internal/host/ssh.go
- internal/host/test_helpers_linux.go
Host interface has no concept of pwd, so accepting any relative paths would be ambiguous.
This PR adds tests for all path related Host interface methods, to check whether it fails with a specific error when a relative path is passed.
commit-id:014a6a18
---
**Stack**:
- #157
- #156
- #155
- #154
- #153 ⬅
> Fix Host not enforcing absolute paths

- host/host.go
- internal/host/agent_grpc_client.go
- internal/host/agent_http_client.go
- internal/host/agent_server_http/api/api.go
- internal/host/agent_server_http/main_linux.go
- internal/host/cmd_run.go
- internal/host/cmd_run_linux_test.go
- internal/host/local_linux.go
- internal/host/test_helpers_linux.go
os.Mkdir does not allow setting all permission bits (eg: sticky). This PR changes the interface to be syscall.Mkdir like, but without umask, so that we can actually set all mode bits.
---
**Stack**:
- #159
- #161
- #160
- #158
- #157
- #156
- #155 ⬅
> Host.Mkdir: change from os to syscall interface

- Makefile
- host/host.go
- internal/host/agent_grpc_client.go
- internal/host/agent_http_client.go
- internal/host/agent_server_grpc/proto/service.proto
- internal/host/cmd_run.go
- internal/host/cmd_run_linux_test.go
- internal/host/local_linux.go
- internal/host/test_helpers_linux.go
- resources/file.go
Move Chmod away from os.FileMode to proper syscall interface, to avoid any cross-os abstraction issues with os.Chmod.
---
**Stack**:
- #159
- #161
- #160
- #158
- #157
- #156 ⬅
> Host.Chmod: change from os to syscall

- host/host.go
- internal/host/agent_grpc_client.go
- internal/host/agent_http_client.go
- internal/host/agent_server_http/main_linux.go
- internal/host/cmd_run.go
- internal/host/cmd_run_linux_test.go
- internal/host/local_linux.go
- internal/host/test_helpers_linux.go
- internal/plan/prep_linux_test.go
- internal/store/host.go
- resources/file.go
Change Host.WriteFile to receive mode bits like os.Chmod, to fix issues with os abstraction preventing some bits from being set (eg: SUID).
---
**Stack**:
- #159
- #161
- #160
- #158
- #157 ⬅
> Host.WriteFile move from os to syscall style

- internal/host/agent_server_http/main_linux.go
Things like `Host.Lstat(ctx, "/")` result in 404, unless we change the regexp from `.+` to `.*`.
---
**Stack**:
- #159
- #161
- #160 ⬅
> Fix HTTP agent with "/" as path argument

- host/host.go
- internal/host/agent_grpc_client.go
- internal/host/agent_http_client.go
- internal/host/agent_server_http/api/api.go
- internal/host/agent_server_http/main_linux.go
- internal/host/cmd_run.go
- internal/host/cmd_run_linux_test.go
- internal/host/local_linux.go
- internal/host/test_helpers_linux.go
- resources/file.go
This type should be uint32 (see [here](https://pkg.go.dev/syscall#Stat_t)), even on 64 bit archs.
commit-id:336fd6ff
---
**Stack**:
- #159
- #165
- #179
- #178
- #176 ⬅
> Change chown arg to uint32

- internal/host/agent_grpc_client.go
- internal/host/agent_http_client.go
- internal/host/agent_server_grpc/main_linux.go
- internal/host/agent_server_http/main_linux.go
- internal/host/agent_server_http/net/net.go
- internal/host/docker_unix.go
- internal/host/ssh.go
- `internal/host/docker_unix.go` fix bad sprintf usage.
- `internal/host/ssh.go` drop unused arguments.
- `internal/host/agent_server_http/net/net.go` rename `Conn` to `IOConn`, as... it is a connection for any I/O object (eg: a pipe).
- `internal/host/agent_http_client.go` improve error catching and reporting for the agent server shutdown.
- `internal/host/agent_grpc_client.go` simplify code a bit, moving client to contructor, fix a potential bug on Close (we shouldn't wait on spawn channel when we fail to ask for shutdown) & misc bits.
---
**Stack**:
- #159
- #165
- #188 ⬅
> Misc fixes & improvements

- .github/workflows/build-darwin.yaml
- .github/workflows/build-linux.yaml
- .github/workflows/pull_request.yaml
- .github/workflows/push.yaml
[GitHub now has arm64 runners ](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/), which can run the arm64 build in [~54s](https://github.com/fornellas/resonance/actions/runs/12817609288/job/35741226828?pr=191#step:7:1) vs in [~22min](https://github.com/fornellas/resonance/actions/runs/12753584021/job/35545562325#step:8:1) when under qemu emulating arm64 under amd64. Let's make use of it.
> Use GH arm runner

- .github/workflows/update_deps.yaml
https://github.com/fornellas/resonance/actions/runs/12858729606
This parameter was missing.
> Fix update deps job

- .github/workflows/build-darwin.yaml
Closes #123.
Extras:
- use consistent name for help targets.
- rename `go` to `install-go` for consistency
- add `install-tools` target, and call it for shell: this ensures the shell always has the correct go version, to prevent issues when go version is updated.
- rename `bulid.sh` to `make.sh`, as it is essentially a make wrapper.
- join all install targets together for easier maintenance.
- fixed broken `protoc-*` clean targets
- added CI check against left over files on cache after clean
- join all generate targets for easier maintenance.
- audo-update protoc with `update-deps` call
- fixed new go version not being installed after it was updated
- fix darwin build wrongly doing go setup (the Makefile manages versions).
---
**Stack**:
- #159
- #209
- #208
- #215
- #216
- #202
- #211
- …
> Auto-update protoc, misc Makefile & CI improvements

- host/host.go
- internal/store/host.go
We should have been using the Host interface, this PR fixes that.
---
**Stack**:
- #159
- #209
- #208
- #215
- #216
- #202
- #211
- #214
- #212
- #204
- #213
- #210
- #207
- #206 ⬅
> Fix store wrongly using os.Mkdirall

- internal/host/agent_client_wrapper.go
In cases where the agent crashes, the agent client will still be fully operational, attempting to read from the pipes, thus hanging forever.
This PR ensures that after the agent exists, we close the associated pipes, thus ensuring the client reading / writing from them can properly exit.
---
**Stack**:
- #159
- #209
- #208
- #215
- #216
- #202
- #211
- #214
- #212
- #204
- #213 ⬅
> Fix client freeze on agent crash

- internal/host/agent_client_wrapper.go
- internal/host/agent_server/main_linux.go
- internal/host/agent_server/proto/service.proto
ATM the agent server runs the command, fully buffers the stdout & stderr in memory, send all of it through the wire, then the agent client copies all of it to the client. This can yield high memory usage for big outputs and is rather slow.
Let's change the implementation, to have the stdout / stderr to be streamed to `Cmd.Stdout` and `Cmd.Stderr` instead, like it already happens for all other host implementations.
---
**Stack**:
- #159
- #209
- #208
- #215
- #216
- #202
- #211
- #214
- #212 ⬅
> Stream AgentClientWrapper.Run stdout/stderr

- host/host.go
- internal/host/lib_linux_test.go
Add tests to cover mode bits not being affected by umask.
---
**Stack**:
- #159
- #209
- #208
- #215
- #216
- #202 ⬅
> Add tests for mode bits

- host/host.go
- host/types.go
- internal/host/agent_client_wrapper.go
- internal/host/agent_server/main_linux.go
- internal/host/agent_server/proto/service.proto
- internal/host/lib/readdir_linux.go
- internal/host/lib_linux_test.go
- internal/host/local_linux.go
Instead of piling up all `DirEnt` in memory, we use channels to stream them to callers.
---
**Stack**:
- #159
- #209
- #208
- #215
- #216 ⬅
> Stream Host.ReadDir results

- host/types.go
- internal/host/agent_client_wrapper_linux_test.go
- internal/host/agent_server/main_linux.go
- internal/host/docker_unix.go
- internal/host/docker_unix_test.go
- internal/host/lib/run_unix.go
- internal/host/lib_linux_test.go
- internal/host/lib_unix_test.go
- internal/host/local_linux_test.go
- internal/host/ssh.go
- internal/host/ssh_linux_test.go
- internal/host/sudo_wrapper_linux_test.go
We were missing tests for Docker, let's add them.
This caught a bug, where the client's environment was being wrongly copied to the target. To fix this, we're now defining a `DefaultEnv`, and having the tests assert for it. This ensures predictability when running commands, as opposed to the client's environment leaking to the target.
---
**Stack**:
- #159
- #209
- #208
- #215 ⬅
> Add tests for Docker

- Makefile
- README.md
This PR adds some extra go build flags that substantially decrease the final binary sizes:
```
$ ls -lh resonance.linux.amd64 internal/host/agent_server/agent_server_linux_*.gz
-rw-rw-r-- 1 fornellas fornellas 7.0M Feb  9 00:34 internal/host/agent_server/agent_server_linux_386.gz
-rw-rw-r-- 1 fornellas fornellas 7.4M Feb  9 00:34 internal/host/agent_server/agent_server_linux_amd64.gz
-rw-rw-r-- 1 fornellas fornellas 6.9M Feb  9 00:34 internal/host/agent_server/agent_server_linux_arm64.gz
-rw-rw-r-- 1 fornellas fornellas 6.7M Feb  9 00:34 internal/host/agent_server/agent_server_linux_arm.gz
-rwxrwxr-x 1 fornellas fornellas  46M Feb  9 00:34 resonance.linux.amd64
$ ls -lh resonance.linux.amd64 internal/host/agent_server/agent_server_linux_*.gz
-rw-rw-r-- 1 fornellas fornellas 3.5M Feb  9 …
```
> Decrease final binary sizes by ~43%

- host/host.go
- internal/blueprint/step.go
- internal/host/agent_client_wrapper.go
- internal/host/agent_server/main_linux.go
- internal/host/agent_server/proto/service.proto
- internal/host/lib_linux_test.go
- internal/host/local_linux.go
- resources/file.go
In order to manage permissions from symlinks, we need `Lchown` as opposed to `Chown`.
---
**Stack**:
- #159
- #209
- #208
- #221 ⬅
> Change Chown to Lchown

- host/agent_client_wrapper.go
- host/agent_server/main_linux.go
- host/agent_server/proto/service.proto
- host/lib_linux_test.go
Pass errno & other specific errors via gRPC and handle them on client.
This enables more generic & flexible `Host` interface usage, as errors can be matched against errno.
---
**Stack**:
- #159
- #209
- #208
- #226 ⬅
> Improve gRPC error reporting

- blueprint/step_linux_test.go
- cmd/apply_linux_test.go
- cmd/plan_linux_test.go
- cmd/validate_linux_test.go
- host/agent_client_wrapper.go
- host/lib/host.go
- host/lib_linux_test.go
- host/local_linux.go
- host/types/file.go
- host/types/host.go
- plan/plan_test.go
- plan/prep_linux_test.go
- resources/file.go
- resources/file_linux_test.go
- resources/resources_test.go
- store/common_linux_test.go
ATM File is pretty basic, and can't handle all diverse cases.
This PR implements support for all file types, so it can actually manage anything.
It also adds `FileMode` type, making it easier to handle file permissions in octal.
---
**Stack**:
- #159
- #209
- #208 ⬅
> File: support all file types

- host/agent_client_wrapper.go
- host/lib/host_linux.go
- host/lib_linux_test.go
- host/local_linux.go
This makes debugging possible, otherwise we just get a generic error such as "permission denied", and no idea where...
---
**Stack**:
- #209
- #241
- #244 ⬅
> Add fs.PathError to all path related Host functions

- cmd/lib.go
- cmd/lib_darwin.go
- cmd/lib_linux.go
- host/ssh.go
- host/ssh_linux_test.go
Ssh client has various extra options which were not exposed. Without them, connecting to hosts may be impossible. Eg:
- `ssh` command has its own list of `HostKeyAlgorithms`.
- `ssh` successfully connects to a host, using one of the algorithms there, and adds the fingerprint to `known_hosts`.
- Go has _its own_ values for that at https://pkg.go.dev/golang.org/x/crypto/ssh#ClientConfig.
- Go may then find a _different_ host key algorithm to connect, and attempts to connect.
- `known_hosts` validation fails with https://pkg.go.dev/golang.org/x/crypto@v0.33.0/ssh/knownhosts#KeyError, because the chosen host key algorithm differs from the key algorithm present on `known_hosts` (added by `ssh` previously).
- The error message is cryptic: `"knownhosts: key mismatch"`.
This PR:
- Wraps around …
> Add missing SSH options

- log/buffered_handler.go
- log/buffered_handler_test.go
This will be useful down the line as we start doing things (like reading host resource state) concurrently.
> Add BufferedHandler

- cmd/plan.go
- host/agent_client_wrapper.go
- host/agent_server/main_linux.go
- host/agent_server/proto/service.proto
- host/net/net.go
- host/types/cmd.go
We randomly hit this case:
```
🖥 Host
type: ssh
name: n2p.local
DEBUG Close
ERROR failed to close host
error:
failed to run /tmp/resonance_agent.L1IPYkml : write |1: broken pipe
Process did not exit:
```
Root cause seems to be race condition between the gRPC client & server, which have left over bufferett things that attempt to go through the SSH session that's ended when the process exits.
This PR changes the shutdown mechanics:
- It asks the agent to shutdown itself by calling the CLI again, and the CLI identifies running process, and asks for them to stop gracefully.
- It makes the agent remove itself, so there's no junk left behind (tangent bug also fixed).
> Fix agent stop race condition

- host/agent_server/main_linux.go
After we close the client, there's a tiny chance the server may try to write to the pipe, so it'll fail with SIGPIPE.
This PR:
- Handles this SIGPIPE.
- Moves the deletion of the file to the `--stop` call, otherwise the binary won't exist when we call it when SIGPIPE happens.
> Fix shutdown race

- host/base_host_unix_test.go
- host/docker_unix.go
- host/ssh.go
- host/sudo_wrapper.go
- host/sudo_wrapper_linux_test.go
We were not consistently reporting this error, this PR makes all cases behave like Local (which is "the correct one").
> Fix Run with bad path
